# Generated by Django 2.0.1 on 2018-02-04 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wired', '0006_device_hide_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='button',
            name='payload',
            field=models.CharField(choices=[('0', '0'), ('1', '1')], max_length=1),
        ),
        migrations.AlterField(
            model_name='device',
            name='gpio',
            field=models.IntegerField(help_text='GPIO port', unique=True),
        ),
    ]
