# Generated by Django 2.0.1 on 2018-06-12 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0003_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('action.devices.types.LIGHT', 'LIGHT'), ('action.devices.types.OUTLET', 'OUTLET')], max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('willReportState', models.BooleanField(default=False)),
                ('roomHint', models.CharField(max_length=255)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='google_device', to='common.BaseDevice')),
            ],
        ),
        migrations.CreateModel(
            name='NickNames',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='google_smart_home.Device')),
            ],
        ),
        migrations.CreateModel(
            name='OnOff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='google_smart_home.Device')),
                ('off', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='google_off', to='common.BaseButton')),
                ('on', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='google_on', to='common.BaseButton')),
            ],
        ),
        migrations.CreateModel(
            name='Traits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trait', models.CharField(choices=[('action.devices.traits.OnOff', 'OnOff')], max_length=255)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='google_smart_home.Device')),
            ],
        ),
    ]
