# Generated by Django 2.0.1 on 2018-06-12 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('google_smart_home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NickNames',
            new_name='NickName',
        ),
        migrations.RenameModel(
            old_name='Traits',
            new_name='Trait',
        ),
    ]
