# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-28 19:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Button',
            fields=[
                ('name', models.CharField(max_length=255)),
                ('count', models.IntegerField(default=10)),
                ('color', models.CharField(choices=[('btn-default', 'White'), ('btn-primary', 'Blue'), ('btn-success', 'Green'), ('btn-info', 'Light blue'), ('btn-warning', 'Orange'), ('btn-danger', 'Red')], default='btn-default', max_length=255)),
                ('row', models.IntegerField(default=0)),
                ('priority', models.IntegerField(default=0)),
                ('parent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='infrared', serialize=False, to='common.BaseButton')),
            ],
            bases=('common.basebutton',),
        ),
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('remote', models.CharField(max_length=255)),
                ('key', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('name', models.CharField(max_length=255, unique=True)),
                ('parent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='infrared', serialize=False, to='common.BaseDevice')),
            ],
            bases=('common.basedevice',),
        ),
        migrations.AddField(
            model_name='button',
            name='config',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buttons', to='infrared.Config'),
        ),
        migrations.AddField(
            model_name='button',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buttons', to='infrared.Device'),
        ),
    ]
