# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-31 11:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrared', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='button',
            name='count',
            field=models.IntegerField(default=2),
        ),
    ]
