# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-28 19:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Button',
            fields=[
                ('name', models.CharField(max_length=255)),
                ('method', models.CharField(max_length=255)),
                ('color', models.CharField(choices=[('btn-default', 'White'), ('btn-primary', 'Blue'), ('btn-success', 'Green'), ('btn-info', 'Light blue'), ('btn-warning', 'Orange'), ('btn-danger', 'Red')], default='btn-default', max_length=255)),
                ('row', models.IntegerField(default=0)),
                ('priority', models.IntegerField(default=0)),
                ('parent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='kodi', serialize=False, to='common.BaseButton')),
            ],
            options={
                'ordering': ['row', 'priority'],
            },
            bases=('common.basebutton',),
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('name', models.CharField(max_length=255, unique=True)),
                ('host', models.CharField(max_length=16)),
                ('port', models.CharField(max_length=16)),
                ('user', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('parent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='kodi', serialize=False, to='common.BaseDevice')),
            ],
            bases=('common.basedevice',),
        ),
        migrations.AddField(
            model_name='button',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buttons', to='kodi.Device'),
        ),
        migrations.AlterUniqueTogether(
            name='button',
            unique_together=set([('name', 'device')]),
        ),
    ]
