# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-04 12:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_auto_20180203_1831'),
    ]

    operations = [
        migrations.AddField(
            model_name='button',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
