# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-31 16:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device_group', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='groupdevicerelation',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
