# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-01 21:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thermometer', '0003_capacitordevice_unit'),
    ]

    operations = [
        migrations.CreateModel(
            name='W1Therm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('unit', models.CharField(blank=True, max_length=254, null=True)),
            ],
        ),
    ]
