# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-03 00:39
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_room'),
    ]

    operations = [
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField()),
                ('name', models.TextField()),
            ],
        ),
    ]
