# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-01-01 20:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Button',
            fields=[
                ('name', models.CharField(max_length=255)),
                ('color', models.CharField(choices=[('btn-default', 'White'), ('btn-primary', 'Blue'), ('btn-success', 'Green'), ('btn-info', 'Light blue'), ('btn-warning', 'Orange'), ('btn-danger', 'Red')], default='btn-default', max_length=255)),
                ('url', models.CharField(max_length=511)),
                ('post_body', models.CharField(blank=True, max_length=511, null=True)),
                ('method', models.CharField(choices=[('post', 'POST'), ('get', 'GET')], max_length=10)),
                ('user', models.CharField(blank=True, max_length=255, null=True)),
                ('password', models.CharField(blank=True, max_length=255, null=True)),
                ('parent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='api', serialize=False, to='common.BaseButton')),
            ],
            bases=('common.basebutton',),
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('name', models.CharField(max_length=255, unique=True)),
                ('parent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='api', serialize=False, to='common.BaseDevice')),
            ],
            bases=('common.basedevice',),
        ),
        migrations.AddField(
            model_name='button',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buttons', to='api.Device'),
        ),
        migrations.AlterUniqueTogether(
            name='button',
            unique_together=set([('name', 'device')]),
        ),
    ]
