# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-01-01 23:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20180102_0020'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
