# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-01-01 23:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_device_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='button',
            name='content_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
