# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-01-02 00:24


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_room'),
        ('api', '0005_auto_20180102_0057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='description',
        ),
        migrations.AddField(
            model_name='device',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='api', to='common.Room'),
        ),
        migrations.AlterField(
            model_name='button',
            name='color',
            field=models.CharField(choices=[('default', 'White'), ('primary', 'Blue'), ('success', 'Green'), ('info', 'Light blue'), ('warning', 'Orange'), ('danger', 'Red')], default='btn-default', max_length=255),
        ),
    ]
