# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-01 19:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0002_capacitordevice'),
    ]

    operations = [
        migrations.AddField(
            model_name='capacitordevice',
            name='unit',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
