# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-14 00:30


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0004_w1therm'),
    ]

    operations = [
        migrations.CreateModel(
            name='MCP3008',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('clk', models.IntegerField(help_text='CLK')),
                ('miso', models.IntegerField(help_text='MISO')),
                ('mosi', models.IntegerField(help_text='MOSI')),
                ('cs', models.IntegerField(help_text='CS')),
            ],
        ),
        migrations.CreateModel(
            name='MCP3008Channel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('type', models.CharField(choices=[('t', 'Thermistor'), ('v', 'Value'), ('p', 'Percent'), ('r', 'Resistance')], default='v', max_length=1)),
                ('unit', models.CharField(blank=True, max_length=254, null=True)),
                ('channel', models.IntegerField(help_text='Channel')),
                ('decimals', models.IntegerField(default=2, help_text='Number of decimals to show')),
                ('series_resistor', models.FloatField(blank=True, default=10.0, help_text='Resistor value in kohm, must be set on Thermistor and Resistance', null=True)),
                ('save_value', models.BooleanField(default=False)),
                ('MCP3008', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sensors.MCP3008')),
            ],
        ),
        migrations.CreateModel(
            name='Readings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_created=True)),
                ('identity', models.CharField(max_length=254)),
                ('value', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='capacitordevice',
            name='last_value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='capacitordevice',
            name='save_value',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dht11',
            name='last_humidity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dht11',
            name='last_temperature',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dht11',
            name='save_humidity',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dht11',
            name='save_temperature',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dht11',
            name='show_humidity',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dht11',
            name='show_temperature',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='w1therm',
            name='save_temperature',
            field=models.BooleanField(default=False),
        ),
    ]
