# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-14 01:14


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0005_auto_20180114_0130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readings',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
