# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-14 11:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0007_auto_20180114_0218'),
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkSensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=511)),
                ('post_body', models.TextField(blank=True, null=True)),
                ('content_type', models.CharField(blank=True, default='application/json', max_length=255, null=True)),
                ('method', models.CharField(choices=[('post', 'POST'), ('get', 'GET')], max_length=10)),
                ('user', models.CharField(blank=True, max_length=255, null=True)),
                ('password', models.CharField(blank=True, max_length=255, null=True)),
                ('decimals', models.IntegerField(default=2, help_text='Number of decimals to show')),
                ('unit', models.CharField(blank=True, max_length=254, null=True)),
                ('response_parameter', models.CharField(blank=True, max_length=254, null=True)),
            ],
        ),
    ]
