# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-28 19:26


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Button',
            fields=[
                ('name', models.CharField(max_length=255)),
                ('rounds', models.IntegerField(default=10)),
                ('color', models.CharField(choices=[('btn-default', 'White'), ('btn-primary', 'Blue'), ('btn-success', 'Green'), ('btn-info', 'Light blue'), ('btn-warning', 'Orange'), ('btn-danger', 'Red')], default='btn-default', max_length=255)),
                ('priority', models.IntegerField(default=0)),
                ('active', models.BooleanField(default=False)),
                ('parent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='radio', serialize=False, to='common.BaseButton')),
            ],
            options={
                'ordering': ['priority'],
            },
            bases=('common.basebutton',),
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('name', models.CharField(max_length=255)),
                ('parent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='radio', serialize=False, to='common.BaseDevice')),
            ],
            bases=('common.basedevice',),
        ),
        migrations.CreateModel(
            name='RadioCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('payload', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='RadioProtocol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('time', models.FloatField(help_text='Period time t in seconds')),
            ],
        ),
        migrations.CreateModel(
            name='RadioSignal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('char', models.CharField(max_length=1)),
                ('on', models.IntegerField(help_text='Nr of periods on')),
                ('off', models.IntegerField(help_text='Nr of periods off')),
                ('protocol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='radio.RadioProtocol')),
            ],
        ),
        migrations.CreateModel(
            name='RadioTransmitter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('gpio', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='radiocode',
            name='protocol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='radio.RadioProtocol'),
        ),
        migrations.AddField(
            model_name='radiocode',
            name='transmitter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='radio.RadioTransmitter'),
        ),
        migrations.AddField(
            model_name='button',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buttons', to='radio.Device'),
        ),
        migrations.AddField(
            model_name='button',
            name='radio_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buttons', to='radio.RadioCode'),
        ),
        migrations.AlterUniqueTogether(
            name='radiosignal',
            unique_together=set([('protocol', 'char')]),
        ),
        migrations.AlterUniqueTogether(
            name='button',
            unique_together=set([('name', 'device')]),
        ),
    ]
