# Generated by Django 2.0.1 on 2018-02-26 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoopiaConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=511)),
                ('password', models.CharField(max_length=511)),
                ('domain', models.CharField(max_length=511)),
                ('subdomain', models.CharField(default='@', max_length=511)),
                ('ttl', models.IntegerField(default=300)),
            ],
        ),
    ]
