# Generated by Django 2.0.1 on 2018-09-10 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dyndns', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loopiaconfig',
            name='type',
            field=models.CharField(choices=[('A', 'A'), ('AAAA', 'AAA')], default='A', max_length=511),
            preserve_default=False,
        ),
    ]
