# Generated by Django 2.0.1 on 2018-02-19 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradfri', '0002_auto_20180219_2331'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='button',
            name='current_value',
        ),
        migrations.AddField(
            model_name='device',
            name='color',
            field=models.IntegerField(default=250),
        ),
        migrations.AddField(
            model_name='device',
            name='dimmer',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='device',
            name='state',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterUniqueTogether(
            name='tradfrilight',
            unique_together={('gateway', 'light_id')},
        ),
    ]
