# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-28 19:26


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ScheduleSlot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_mode', models.CharField(choices=[('t', 'Time'), ('u', 'Sun up'), ('d', 'Sun down')], default='t', max_length=1)),
                ('start', models.TimeField(blank=True, null=True)),
                ('end_mode', models.CharField(choices=[('t', 'Time'), ('u', 'Sun up'), ('d', 'Sun down')], default='t', max_length=1)),
                ('end', models.TimeField(blank=True, null=True)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedules.Schedule')),
            ],
        ),
    ]
