# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-30 20:30


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('schedules', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='device',
            field=models.ManyToManyField(to='common.BaseDevice'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='off',
            field=models.ManyToManyField(related_name='schedule_off', to='common.BaseButton'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='on',
            field=models.ManyToManyField(related_name='schedule_on', to='common.BaseButton'),
        ),
    ]
