# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-30 23:16


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('schedules', '0003_auto_20171230_2212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='off',
        ),
        migrations.AddField(
            model_name='schedule',
            name='off',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedule_off', to='common.BaseButton'),
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='on',
        ),
        migrations.AddField(
            model_name='schedule',
            name='on',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedule_on', to='common.BaseButton'),
        ),
    ]
