# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-30 23:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('schedules', '0004_auto_20171231_0016'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='device',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='common.BaseDevice'),
        ),
    ]
