# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-31 01:23


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0005_schedule_device'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='disable_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='last_action',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='repeat_signal',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='off',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedule_off', to='common.BaseButton'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='on',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedule_on', to='common.BaseButton'),
        ),
    ]
