# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-31 15:54


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0006_auto_20171231_0223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='name',
        ),
    ]
