# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-01-01 20:15


import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0007_remove_schedule_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduleslot',
            name='end',
            field=models.FloatField(default=0, help_text='Time between 00:00 and 23:59, expressed as decimal numbers ex: 12:15 = 12.25. May be negative if start mode is not set to time to add an offset.', validators=[django.core.validators.MinValueValidator(-23.99), django.core.validators.MaxValueValidator(23.99)]),
        ),
        migrations.AlterField(
            model_name='scheduleslot',
            name='start',
            field=models.FloatField(default=0, help_text='Time between 00:00 and 23:59, expressed as decimal numbers ex: 12:15 = 12.25. May be negative if start mode is not set to time to add an offset.', validators=[django.core.validators.MinValueValidator(-23.99), django.core.validators.MaxValueValidator(23.99)]),
        ),
    ]
